version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEnd
    image: djalmafelipe/frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://node:5000
    networks:
      - app-network

  backend:
    build:
      context: ./BackEnd
    image: djalmafelipe/backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=1234
      - DB_NAME=postgres
      - DB_PORT=5432
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
